### PR TITLE
Implement templates

### PR DESCRIPTION
**Pull request by smn**

### CODE REVIEW

**Comment by bruskiza** [comment]
:+1:

**Comment by miltontony** [comment]
@bruskiza I don't think there's anything to merge just yet.. :smile:

**Comment by bruskiza** [comment]
@saeedmb8 :+1: from me... can't really see too much harm. CSS added... images changed and template updated.

**Comment by smarzban** [comment]
@bruskiza templates work not done yet, these are the small changes, still more to be done :)

**Comment by miltontony** [comment]
@saeedmb8 might be better to merge what you have and start another PR. Otherwise this PR is going to grow really big

**Comment by smn** [comment]
:+1: on merging this now and focussing on smaller PRs going forward.

**Comment by smarzban** [comment]
@miltontony sorry I saw your comment after I pushed my last changes, will do that now @smn sure

**Pull request merged**
