### PR TITLE
add hide class to menu items without waiting for js

### PR DESCRIPTION
**Pull request by KaitCrawford**

### CODE REVIEW

**Comment by KaitCrawford** [comment]
@bruskiza @miltontony @smn

**Comment by KaitCrawford** [comment]
small review

**Comment by miltontony** [comment]
:+1:

**Comment by smn** [comment]
I suspect this may have been intentionally the other way around so that browsers who don't support JS well but do hide elements through CSS will have the menu visible by default.

I'm worried though that the way it was implemented was that it would overlay the elements instead of insert them, effectively hiding other UI elements when the menu was displayed by default.

Not a :+1: or a :-1: just giving some context to why these things sometimes are implemented this way.

**Comment by KaitCrawford** [comment]
@smn good point. I'd forgotten to think about the js-disabled case. However, before this change devices without js would never be able to see anything besides the menu. I think there probably needs to be a design discussion around how the menu's should function without javascript.

**Comment by miltontony** [comment]
@smn there's a special menu for features phones on [line 10](https://github.com/praekelt/molo-tuneme/blob/develop/tuneme/templates/base.html#L10-L17) which is hidden for Smart phones so this shouldn't affect it.

**Comment by smn** [comment]
:+1:

**Pull request merged**
