### PR TITLE
move position of anchor tag for feature phone menu

### PR DESCRIPTION
**Pull request by g1039**

### CODE REVIEW

**Comment by g1039** [comment]
@saeedmb8 @miltontony Ready for review

**Comment by g1039** [comment]
@miltontony @saeedmb8 Ready for re-review

**Comment by smarzban** [comment]
@miltontony @TrevorOctober I don't think this is necessarily to do, heights of menu and footer is 205px  and I think is long enough to cover the biggest feature phone screens, so in anycase the menu would be sitting at the top of any screen. what are your thoughts on this?

**Comment by miltontony** [comment]
:+1: 
I think this should be fine - it's a really small thing. I doubt if anyone will notice actually.

**Comment by smarzban** [comment]
:+1:

**Pull request merged**
