### PR TITLE
new version update

### PR DESCRIPTION
**Pull request by g1039**
Ready for review

### CODE REVIEW

**Comment by rudigiesler** [comment]
I'm not sure that we want to be pinning all the versions. I would suggest something more like `molo.commenting<0.3.0>=0.2.11`. @miltontony What are your thoughts on this?

**Comment by miltontony** [comment]
@rudigiesler we're trying to move away from unpinned dependencies because docker containers are built from scratch and so 1 day you might be on version 2.9 and the next it'll pull 2.10 if you didn't pin it.

I'm much happier to pin all the things so that we know explicitly which version is running at any given time.

**Comment by miltontony** [comment]
:+1:

**Comment by rudigiesler** [comment]
In that case, :+1: from me too

**Pull request merged**
