### PR TITLE
Add sections to HP

### PR DESCRIPTION
**Pull request by smarzban**

### CODE REVIEW

**Comment by smarzban** [comment]
@bruskiza @smn @miltontony ready for review

**Comment by smarzban** [comment]
feature

**Comment by smarzban** [comment]
smart

**Comment by smarzban** [comment]
@smn @miltontony @bruskiza I removed the sections from homepage and left it with only the latest, as the github design. It's ready for review :)

**Comment by miltontony** [comment]
:+1:

**Pull request merged**
