### PR TITLE
Add search functionality 

### PR DESCRIPTION
**Pull request by smarzban**

### CODE REVIEW

**Comment by smarzban** [comment]
@miltontony @bruskiza 
search

**Comment by smn** [comment]
tune-me-search

works for me locally? Did you run `./manage.py update_index` after editing the articles?

**Comment by smn** [comment]
@saeedmb8 I've renamed (and split) your tests.py file into two files called `test_*.py`, we use `py.test` to run our tests and by default (unless configured otherwise) only runs tests in files named `test_*.py`.

**Comment by smn** [comment]
:+1: from me, we can address the test code coverage for search when we add it to molo.core as a standard feature.

**Comment by smarzban** [comment]
@smn: Yes, the problem was that I didn't do `./manage.py update_index` and Milton told me on Friday. Thanks for all the changes :)

**Pull request merged**
