### PR TITLE
Comment display not working

### PR DESCRIPTION
**Pull request by KaitCrawford**
A user can submit a comment but it is not displayed.

### CODE REVIEW

**Comment by KaitCrawford** [comment]
@bruskiza @saeedmb8 @miltontony
I basically implemented the comment display to work the same way as in b-wise

**Comment by bruskiza** [comment]
:+1: if it paginates on more than 5 comments

**Comment by KaitCrawford** [comment]
@bruskiza working on implementing that as per the SoW next :smile:

**Comment by miltontony** [comment]
:+1:

**Comment by KaitCrawford** [comment]
I'm going to merge this and handle the pagination as a separate issue and PR since it requires changes to the molo-commenting module as well

**Pull request merged**
