### PR TITLE
Add content rotation 

### PR DESCRIPTION
**Pull request by smarzban**

### CODE REVIEW

**Comment by smarzban** [comment]
@miltontony ready for review :)

**Comment by miltontony** [comment]
@saeedmb8 I can't approve this - we need to move `tasks.py` into `molo/core/tasks.py` so that we don't have to scaffold it each time.. that will need a new version bump too

**Comment by smarzban** [comment]
@miltontony ready for review

**Comment by miltontony** [comment]
:+1:

**Comment by smarzban** [comment]
@miltontony ready for review :)

**Comment by miltontony** [comment]
`tuneme/celery.py` is not being used anywhere so you should remove it

**Comment by smarzban** [comment]
@miltontony ready for review :)

**Comment by miltontony** [comment]
:+1:

**Pull request merged**
