### PR TITLE
Use gulp for cache-busting

### PR DESCRIPTION
**Pull request by justinvdm**
We would like to use gulp for our asset processing, as it gives us more control and more options for asset processing than we can get from django addons for doing this.

At the moment, the only asset pipeline step not in gulp is the cache-busting step. We use django-compressor for this step. We are coming across all kinds of weird issues when trying to use these two things together. Since it would be more ideal for all parts of the asset processing pipeline to be done with gulp, I thought it would be better to spend the time getting cache busting with gulp, rather than spending the time fixing issues for a solution we maybe do not want for the long term anyways.

This PR introduces a new django dependency in order for us to read the cache manifest built by gulp: [django-gulp-rev](https://github.com/olasitarska/django-gulp-rev). Since it is meant for use with gulp, it fits in quite well, looks tested, and is quite small and simple. I do not thinking adding this dependency is a concern.

@Mitso @saeedmb8 ready for review

### CODE REVIEW

**Comment by Mitso** [comment]
@justinvdm is this a correct way of loading the versioned stylesheets?
Otherwise it's 💯 

screenshot 2016-10-21 10 02 05

**Comment by justinvdm** [comment]
> @justinvdm is this a correct way of loading the versioned stylesheets?

@Mitso well spotted. [django-gulp-rev](https://github.com/olasitarska/django-gulp-rev) generates those kinds of urls in dev and uses the versioned files gulp as built in prod. Because of this, I've also set things up in gulp so that the unversioned file is sourcemapped for dev (the versioned file isn't).

**Comment by justinvdm** [comment]
We seem to now have django compressor versioning our files the way we want without any issues, so I'm closing this for now. We can always re-open it if we need it.

**Comment by justinvdm** [comment]
For some reason github isn't showing the latest commits for this PR (travis seems to know about them). Re-opening and re-closing to see if that helps, sorry for the noise.

**Pull request closed without merging**
