### PR TITLE
fix image in latest 

### PR DESCRIPTION
**Pull request by smarzban**

### CODE REVIEW

**Comment by smarzban** [comment]
@smn @bruskiza ready for review

**Comment by smn** [comment]
:+1: 

It would probably be easier if we wrote a template tag to make all this image retrieval easier. It looks like we need to be doing that a lot and having a way of finding the image on any of the parents / ancestors is probably going to save a lot of time & confusion.

**Comment by smn** [comment]
But we can look at that next week.

**Comment by smarzban** [comment]
@smn yes, I'm agree will do that :)

**Pull request merged**
