### PR TITLE
Add publish_scheduled_pages to Celery Beat Schedule

### PR DESCRIPTION
**Pull request by g1039**

### CODE REVIEW

**Comment by g1039** [comment]
@saeedmb8 Please review cc @miltontony

**Comment by codiebeulaine** [comment]
@Ntu2koTrevor have you tested this locally with celery?

**Comment by miltontony** [comment]
@Ntu2koTrevor @codiebeulaine I've already added this here https://github.com/praekelt/molo-tuneme/blob/develop/docker/settings.py#L61-L65

**Comment by g1039** [comment]
Ok. Cool. @miltontony should i create a new release for molo?

**Pull request closed without merging**
