### PR TITLE
Change the way articles are presented in the Latest section [YEP-121]

### PR DESCRIPTION
**Pull request by smarzban**

### CODE REVIEW

**Comment by smarzban** [comment]
@bruskiza @miltontony In Tune Me homepage we now have two sections:
1) In the Latest section, you can promote the latest articles and will order them by the latest or the most recently promoted article. In order to achieve this I had to change the 'order_by' in latest_articles function in molo.core #https://github.com/praekelt/molo/pull/45 .

2)In the Featured section, you can promote featured articles on the homepage. Please note that if there isn't an article featured in a category, the category name will still be shown in the homepage.

**Comment by smarzban** [comment]
tuneme homepage

**Comment by smarzban** [comment]
@miltontony ready for review :)

**Comment by miltontony** [comment]
:+1:

**Comment by smarzban** [comment]
@bruskiza @miltontony small change to the section headers :)

**Comment by miltontony** [comment]
:+1:

**Pull request merged**
