### PR TITLE
Fix menu colours 

### PR DESCRIPTION
**Pull request by smarzban**

### CODE REVIEW

**Comment by smarzban** [comment]
@miltontony @smn @bruskiza ready for review :)

**Comment by bruskiza** [comment]
img src="{% static 'img/profile.png' %}" width="35" shouldn't that be handled in the CSS? but otherwise +1 when travis.

**Comment by miltontony** [comment]
:+1:

**Comment by smarzban** [comment]
@bruskiza I had to do some hard coding in order to get the menu colors right

**Pull request merged**
