### PR TITLE
yep-80 default year in dropdown

### PR DESCRIPTION
**Pull request by miltontony**

### CODE REVIEW

**Comment by miltontony** [comment]
@saeedmb8 review please
I ended up going with a forms solution instead of doing it in the templates.

**Comment by smarzban** [comment]
@miltontony brilliant :+1:

**Comment by smarzban** [comment]
@miltontony can you leave the PR open to I also fix the alignment?

**Comment by miltontony** [comment]
:+1: cool

**Comment by smarzban** [comment]
@bruskiza @miltontony ready for review

**Comment by bruskiza** [comment]
:+1:

**Pull request merged**
